org: firsttracksolutiontechnologies
app: firsttrackexpress
service: backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: api
  environment:
    JWT_SECRET : 16c3404b4f53e143d02889ec43c8ca90d37f10418a9b3947b916e6090d973d9c
    DB_HOST : localhost
    DB_USER : root
    DB_PASSWORD : root
    DB_NAME : firsttrackexpress
    EMAIL_USER : sofiyashaikh125@gmail.com
    EMAIL_PASS : sofi9152
    PORT : 5000
    VITE_APP_API_URL : /.netlify/functions/server
functions:
  server:
    handler: server.handler
    memorySize: 512
    timeout: 30
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
plugins:
  - serverless-offline
  - serverless-dotenv-plugin